apiVersion: v2
name: <CHARTNAME>
description: A Helm chart for Kubernetes
type: application
version: 0.4.0
appVersion: "0.4.0"
dependencies:
- name: mychart4
  version: "0.1.0"
  repository: "https://stacksimplify.github.io/helm-charts/"
