apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart9.fullname" . }}
  labels:
    {{- include "mychart9.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "mychart9.selectorLabels" . | nindent 4 }}
